Quiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('main/', views.main),
    path('main2/', views.main2),
]

blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'
urlpatterns = [
    path('index/',views.index, name='index'),
    path('index2/',views.index2, name='index2'),
]

board/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

# from .views import FileDownloadView

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('index2/', views.index2, name='index2'),
    path('<int:question_id>/', views.detail, name='detail'),
    path(
        'answer/create/<int:question_id>/', views.answer_create,
        name='answer_create'),
    # path('question/create/', views.question_create, name='question_create'),

    path('<int:question_id>/update/',views.update, name="update"),
    path('<int:question_id>/delete/',views.delete, name="delete"),
    path('upload3/', views.upload3, name='upload3'),
    path('upload4/', views.upload4, name='upload4'),
    path('download/<int:question_id>/', views.download, name='download'),
    path('<int:answer_id>/answer_delete/',views.answer_delete, name="answer_delete"),
    # path('download/%3Fid=<int:question_id>/', views.download, name='download'),
    # path('download/', views.download, name='download'),
    # path('document/<int:document_id>/', FileDownloadView.as_view(), name="download"),
]

config/urls.py
from xml.etree.ElementInclude import include # 이진호가 추가함
from django.contrib import admin
from django.urls import path, include
from main import views
from userapp import views #이진호가 추가함
from django.conf.urls.static import static #이진호 추가 필수
from django.conf import settings #이진호 추가 필수
# from . import views as config_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('auth/', include('userapp.urls')),
    path('rank/', include('rank.urls')),
    path('quiz/', include('Quiz.urls')),
    path('blog/', include('blog.urls')),
    path('file/', include('file.urls')),
    path('board/', include('board.urls')),
    path('freeboard/', include('freeboard.urls')),
    path('paging/', include('paging.urls')),
    path('study/', include('study.urls')),
    path('youtubeboard/', include('youtubeboard.urls')),
    path('chat/', include('chat.urls')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'
urlpatterns = [
    path('index/', views.index , name="index"),
    path('index2/', views.index2 , name="index2"),
    path('search/',views.search,name='search')
    
]

rank/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "rank"

urlpatterns = [
    path('rank1_100/', views.rank1_100, name = "rank1_100"),
    path('rank2_100/', views.rank2_100, name = "rank2_100"),
    path('insert/', views.insert),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

study/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
app_name = "study"

urlpatterns = [
    path('studying/', views.studying, name = "studying"),
    path('studying2/', views.studying2, name = "studying2"),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

youtubeboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "youtubeboard"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name = "index"),
    path('index2/', views.index2, name = "index2"),
]

board/models.py
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField()
    username = models.CharField(max_length=200)
    file = models.FileField(null=True, blank=True)
    # file = models.FileField(upload_to='%Y/%m/%d', null=True)

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    username = models.CharField(max_length=200)

board/forms.py
from django import forms
from .models import Question, Answer

class QuestionForm(forms.ModelForm):
    # upload = forms.FileField(label='첨부 파일', required=False, 
    #       widget=forms.FileInput(attrs={'class': 'form'}))
    class Meta:
        model = Question
        fields = ['subject', 'content', 'file']
       
        labels = {
            'subject': '제목',
            'content': '내용',
            
        }
        def __init__(self, *args, **kwargs):
            super(PostForm, self).__init__(*args, **kwargs)
            self.fields['file'].required = False
        # exclude = ['file']


class AnswerForm(forms.ModelForm):
    
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
        'content': '답변내용',
        }



# class UploadFileForm(forms.ModelForm):
#     class Meta:
#         model = Question
#         fields = ['file']

board/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Answer, Question
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.shortcuts import redirect
from userapp.models import User
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required #로그인여부
from django.views.generic.detail import SingleObjectMixin
from django.http import FileResponse
from django.core.files.storage import FileSystemStorage
from userapp.models import User


def index(request):
    now_page = request.GET.get('page', 1)
    question_list = Question.objects.order_by('-pub_date')
    p = Paginator(question_list, 10)
    info = p.get_page(now_page)
    # context = {'question_list': question_list}
    start_page = (int(now_page) - 1) // 10 * 10 + 1
    end_page = start_page + 9
    if end_page > p.num_pages:
        end_page = p.num_pages

    context = {'info': info,
        'page_range' : range(start_page, end_page + 1)
    }
    return render(request, 'board/question_list.html', context)

def index2(request):
    now_page = request.GET.get('page', 1)
    question_list = Question.objects.order_by('-pub_date')
    p = Paginator(question_list, 10)
    info = p.get_page(now_page)
    # context = {'question_list': question_list}
    start_page = (int(now_page) - 1) // 10 * 10 + 1
    end_page = start_page + 9
    if end_page > p.num_pages:
        end_page = p.num_pages

    context = {'info': info,
        'page_range' : range(start_page, end_page + 1)
    }
    return render(request, 'board/question_list2.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    context = {
        'question': question
    }
    return render(request, 'board/question_detail.html', context)


from .forms import AnswerForm
@login_required (login_url='userapp:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.username = request.user.username
            answer.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = AnswerForm()
    
    context = {'question': question, 'form': form}
    
    return render(request, 'board/question_detail.html', context)


from .forms import QuestionForm
# def question_create(request):
#     if request.method == 'POST':
#         form = QuestionForm(request.POST)
#         # if form.is_valid():
#         question = form.save(commit=False)
#         question.pub_date = timezone.now()
#         question.username = request.user.username
#         question.save()
#         return redirect('board:index')
#     else:
#         form = QuestionForm()

#     context = {'form': form}

#     return render(request, 'board/question_form.html', context)

@login_required (login_url='userapp:login')
def upload3(request):
    user = User.objects.get(username = request.user.username)   
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
             
        if form.is_valid():
            uploadFile = form.save(commit=False)
            if uploadFile.file:        
                name = uploadFile.file.name 
                size = uploadFile.file.size                              
            uploadFile.pub_date = timezone.now()
            uploadFile.username = request.user.username
            uploadFile.save()
            user.score = user.score + 10
            user.save()
            return redirect('board:index')
    else:
        form = QuestionForm()
    return render(
        request, 'board/question_form.html', {'form': form})

@login_required (login_url='userapp:login2')
def upload4(request):
    user = User.objects.get(username = request.user.username)   
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
             
        if form.is_valid():
            uploadFile = form.save(commit=False)
            if uploadFile.file:        
                name = uploadFile.file.name 
                size = uploadFile.file.size                              
            uploadFile.pub_date = timezone.now()
            uploadFile.username = request.user.username
            uploadFile.save()
            user.score = user.score + 10
            user.save()
            return redirect('board:index2')
    else:
        form = QuestionForm()
    return render(
        request, 'board/question_form2.html', {'form': form})

def update(request, question_id):
    question = Question.objects.get(id=question_id)
    if(question.username == request.user.username):
        if request.method == "POST":
            question.subject = request.POST['subject']
            question.content = request.POST['content']
            question.pub_date = timezone.now()
            
            question.save()
            return redirect('board:index')
        else:
            question=Question()
            return render(request, 'board/update.html', {'question':question})
    else :
        return render(request, 'board/warning.html')


def delete(request, question_id):
    question = Question.objects.get(id=question_id)
    if(question.username == request.user.username):
        question.delete()
        return redirect('board:index')
    return render(request, 'board/warning.html')


def answer_delete(request,answer_id):
    comment = Answer.objects.get(id=answer_id)
    if(comment.username == request.user.username):
        comment.delete()
        return redirect('board:index')
    return render(request, 'board/warning.html')

# def download(request):
#     question = get_object_or_404(Question, id=question_id)
   
#     # file_url = urllib.parse.unquote(url)
#     filepath = str(settings.BASE_DIR) + ('/media/%s' % question.file.name)
#     filename = os.path.basename(filepath)
#     context = {
#         'question': question
#     }
#     with open(filepath, 'rb') as f:
#         response = HttpResponse(f, content_type='application/octet-stream')
#         response['Content-Disposition'] = 'attachment; filename=%s' % filename
#         return render(request, 'board/question_detail.html', context)

    
#     return render(request, 'board/question_detail.html', context)

    # id = request.GET.get('id')
    # question = Question.objects.get(id=id)
    # filepath = str(settings.BASE_DIR) + ('/media/%s' % question.file.name)
    # filename = os.path.basename(filepath)
    # with open(filepath, 'rb') as f:
    #     response = HttpResponse(f, content_type='application/octet-stream')
    #     response['Content-Disposition'] = 'attachment; filename=%s' % filename
    #     return response

from config import settings
import os
def download(request,question_id):   
    
    question = get_object_or_404(Question, pk=question_id)
    if question.file:
        file_url = question.file.url[1:]
        # filepath = str(settings.BASE_DIR) + ('/media/%s' % question.file.name)   
        if os.path.exists(file_url) :
            with open(file_url, 'rb') as f:
                filename = os.path.basename(file_url)
                response = HttpResponse(f, content_type='application/octet-stream')
                response['Content-Disposition'] = 'attachment; filename=%s' % filename
                return response
    else :  
        return render(request, 'board/delete.html')

board/templates/board/delete.html
<script>
    alert("파일이 없습니다.")
    window.history.back() 
</script>

board/templates/board/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<!doctype html>
<html lang="en">

<head>
    <title>질문답변게시판 - 게시글</title>
    <meta charset="utf-8">
    <link rel ="icon" type="image/x-icon" href="/static/img/ktlogo.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   
    <link rel="stylesheet" href="/static/css/style.css"> 
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/static/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/style_rank.css" type="text/css">
</head>

<body>

        <!-- Header Section Begin -->
        <header class="header">
            <div class="header__top">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="header__top__left">
                                <ul>
                                 
                                    
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="header__top__right">
                                <div class="header__top__right__social">
                                    <a href="https://instagram.com/aivlestory?utm_medium=copy_link "target='_blank' ><i class="fa fa-instagram fa-2x" aria-hidden= "true"></i></a>
                                    <a href="https://classum.com/"target='_blank' ><i class="fa fa-copyright fa-2x" aria-hidden="true"></i></a>
                                    <a href="https://blog.naver.com/porory_rei"target='_blank' ><i class="fa fa-bold fa-2x" aria-hidden="true"></i></a>
                                    <a href="https://ktedu.kt.com/aivle/about.html"target='_blank' ><i class="fa fa-home fa-2x" aria-hidden="true"></i></a>
                                </div>
                                <div class="header__top__right__language">
                                    <img src="img/language.png"alt="">
                                    <div>AI 개발자</div>
                                    <span class="arrow_carrot-down"></span>
                                    <ul>
                                        <li><a href="{% url 'main:index' %}">AI 개발자</a></li>
                                        <li><a href="{% url 'main:index2' %}">DX 컨설턴트</a></li>
                                    </ul>
                                </div>
                    
                                    {% if user.is_authenticated %}
                                      
                                    <div class="header__top__right__auth">
                                        <a href="{% url 'userapp:logout' %}"><i class="fa fa-user"></i> logout</a>
                                    </div> 
                                    
                                   
                                    
      
                                    {% else %}
                                    <div class="header__top__right__auth">
                                        <a href="{% url 'userapp:login' %}"><i class="fa fa-user"></i> Login</a>
                                    </div>
                                    {% endif %}
      
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="header__logo">
                            <a href="{% url 'main:index' %}"><img src="/static/img/aivle.PNG" class="mt-2"></a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <nav class="header__menu">
                            <ul>
                                <li class="active"><a href="{% url 'main:index' %}">홈</a></li>
                                <li><a href="/chat/chat_1">채팅</a></li>
                                <li><a href="#">커뮤니티</a>
                                    <ul class="header__menu__dropdown">
                                       
                                        <li><a href="{% url 'board:index' %}">Q&A</a></li>
                                        <li><a href="{% url 'freeboard:index' %}">자유게시판</a></li>
                                        <li><a href="{% url 'blog:index' %}">정보방</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'rank:rank1_100' %}">랭킹 TOP 100</a></li>
                                  <li><a href="">학습</a>
                                      <ul class="header__menu__dropdown">
                                          <li><a href="{% url 'study:studying' %}">AIVLE 강의</a></li>
                                          <li><a href="{% url 'youtubeboard:index' %}">YOUTUBE 강의</a></li>   
                                      
                                      </ul>   
                              
                                  
                              </li>
                                <li><a href="/quiz/main">퀴즈</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div class="col-lg-3">
                        <div class="header__cart">
                            
                              <a><i class="fa fa-user-circle fa-2x" aria-hidden= "true"></i></a>
                              <b>　{{user.username}}님</b>　 <b>score:</b> <span>{{user.score}}</span>
                           
                            
                        </div>
                    </div>
                </div>
                <div class="humberger__open">
                    <i class="fa fa-bars"></i>
                </div>
            </div>
        </header>
        <!-- Header Section End -->
      

<div class="container my-3">
    <br>
  
    <br>

    <h3 class="border-bottom py-2">  <img src="/static/img/q.jpg"> <b>{{ question.subject }}</b>
        <br></h3>
     
        <div class="card shadow mb-4" >
            <div class="card-header py-3"  >
                <b style='color: #000000'>
                      작성자 ID : <b>{{question.username}}</b>
            </div>
            
                <div class="card-text" style="white-space: pre-line;">
                    　{{ question.content }}
                </div>
                <div class="card-body">
                <div class="d-flex justify-content-end">
                    <div class="badge badge-light p-2">
    
    
                        {{ question.pub_date }}
                        <br><br>
                   
                    </div>
                    
                </div>
            </div>
        </div>

       
    <br>
   <h4 class="border-bottom my-2 py-2">
        <div><img src="/static/img/A.png"><b>
            등록된 답변</div>
    </b></h4>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"> <span style="background: linear-gradient(to top, #FFE400 30%, transparent 70%)">{{question.answer_set.count}}개</span>의 답변</h6>
        </div>
        <div class="card-body">
        
            <div>
                
            </div>

    {% for answer in question.answer_set.all %}
    <div class="card shadow mb-4">
        <div class="card-header py-3" >
            <b style='color: #FF1244'>
                작성자 : {{ answer.username }} </b>
                <a href="{% url 'board:answer_delete' answer.id %}" class="btn btn-primary" style="float:right"onClick="alert('삭제되었습니다.')">삭제</a>
        </div>
        
            <div class="card-text" style="white-space: pre-line;">
                　 {{ answer.content }}
            </div>
            <div class="card-body">
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">


                    {{ answer.create_date }}
                    <br><br>
               
                </div>
                
            </div>
        </div>
    </div>
    {% endfor %}
    
    
    <form action="{% url 'board:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}

        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="7" placeholder="내용을 입력해주세요"></textarea>
        </div>
        <div style='text-align:right;'>
            <input type="submit" value="답변등록" class="btn btn-primary">
            <a href="{% url 'board:index' %}" class="btn btn-primary">
                목록으로
            </a>
            <a href="{% url 'board:download' question.id %}" class="btn btn-primary">다운로드</a>           
            <a href="{% url 'board:update' question.id %}" class="btn btn-primary">수정</a>
            <a href="{% url 'board:delete' question.id %}" class="btn btn-primary">삭제</a>
        </div>
    </form>
    <div>
       
        </form>
       
     </div>
    <br><br>
    </div>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/main.js"></script>

</body>

board/templates/board/question_form2.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <title>질문답변게시판 - 질문등록</title>
    <meta charset="utf-8">
    <link rel ="icon" type="image/x-icon" href="/static/img/ktlogo.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   
    <link rel="stylesheet" href="/static/css/style2.css"> 
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/static/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/style_rank2.css" type="text/css">
</head>

<body>

  <!-- Header Section Begin -->
  <header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="header__top__left">
                        <ul>
                           
                            
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="header__top__right">
                        <div class="header__top__right__social">
                            <a href="https://instagram.com/aivlestory?utm_medium=copy_link "target='_blank' ><i class="fa fa-instagram fa-2x" aria-hidden= "true"></i></a>
                            <a href="https://classum.com/"target='_blank' ><i class="fa fa-copyright fa-2x" aria-hidden="true"></i></a>
                            <a href="https://blog.naver.com/porory_rei"target='_blank' ><i class="fa fa-bold fa-2x" aria-hidden="true"></i></a>
                            <a href="https://ktedu.kt.com/aivle/about.html"target='_blank' ><i class="fa fa-home fa-2x" aria-hidden="true"></i></a>
                        </div>
                        <div class="header__top__right__language">
                            <img src="img/language.png"alt="">
                            <div>DX 컨설턴트</div>
                            <span class="arrow_carrot-down"></span>
                            <ul>
                                <li><a href="{% url 'rank:rank2_100'%}">DX 컨설턴트</a></li>
                                <li><a href="{% url 'rank:rank1_100'%}">AI 개발자</a></li>
                            </ul>
                        </div>
            
                            {% if user.is_authenticated %}
                              
                            <div class="header__top__right__auth">
                                <a href="{% url 'userapp:logout' %}"><i class="fa fa-user"></i>logout</a>
                             
                            </div> 
                           
            

                            {% else %}
                            <div class="header__top__right__auth">
                                <a href="{% url 'userapp:login2' %}"><i class="fa fa-user"></i> Login</a>
                            </div>
                            {% endif %}

                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="header__logo">
                    <a href="{% url 'main:index2' %}"><img src="/static/img/aivle.PNG" class="mt-2"></a>
                </div>
            </div>
            <div class="col-lg-6">
                <nav class="header__menu">
                    <ul>
                        <li class="active"><a href="{% url 'main:index2' %}">홈</a></li>
                        <li><a href="/chat/chat_1">채팅</a></li>
                        <li><a href="#">커뮤니티</a>
                            <ul class="header__menu__dropdown">
                               
                                <li><a href="{% url 'board:index2' %}">Q&A</a></li>
                                <li><a href="{% url 'freeboard:index2' %}">자유게시판</a></li>
                                <li><a href="{% url 'blog:index2' %}">정보방</a></li>
                                
                            </ul>
                        </li>
                        <li><a href="{% url 'rank:rank2_100' %}">랭킹 TOP 100</a></li>
                        <li><a href="">학습</a>
                            <ul class="header__menu__dropdown">
                                <li><a href="{% url 'study:studying2' %}">AIVLE 강의</a></li>
                                <li><a href="{% url 'youtubeboard:index2' %}">YOUTUBE 강의</a></li>   
                            
                                </ul>
                            </li>
                        <li><a href="/quiz/main2">퀴즈</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3">
                <div class="header__cart">
                    <ul>
                        <a><i class="fa fa-user-circle fa-2x" aria-hidden= "true"></i></a>
                        <b>　{{user.username}}님</b>　 <b>score:</b> <span>{{user.score}}</span>
                    </ul>
                   
                </div>
            </div>
        </div>
        <div class="humberger__open">
            <i class="fa fa-bars"></i>
        </div>
    </div>
</header>
<!-- Header Section End -->

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form class="post-form my-3" action="{% url 'board:upload3' %}" method="post"
    enctype="multipart/form-data" > 
        {% csrf_token %}
        
        <!-- 오류표시 Start -
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
         오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>

            
            <textarea name="content" id ="content" class="form-control" rows="10"
            placeholder = "내용을 입력해주세요"></textarea> 

            <input type="file" name="file">
            
        </div>
        <div style='text-align:right;'>
            <br><button type="submit" class="btn btn-primary">저장하기</button>
            <a href="{% url 'board:index' %}" class="btn btn-primary">
                목록으로
            </a>
        </div>
        </form>
        </div>
        <script src="/static/js/jquery.min.js"></script>
        <script src="/static/js/popper.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
        <script src="/static/js/main.js"></script>
    </body>