Quiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('main/', views.main),
    path('main2/', views.main2),
]

blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'
urlpatterns = [
    path('index/',views.index, name='index'),
    path('index2/',views.index2, name='index2'),
]

board/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

# from .views import FileDownloadView

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('index2/', views.index2, name='index2'),
    path('<int:question_id>/', views.detail, name='detail'),
    path(
        'answer/create/<int:question_id>/', views.answer_create,
        name='answer_create'),
    # path('question/create/', views.question_create, name='question_create'),

    path('<int:question_id>/update/',views.update, name="update"),
    path('<int:question_id>/delete/',views.delete, name="delete"),
    path('upload3/', views.upload3, name='upload3'),
    path('upload4/', views.upload4, name='upload4'),
    path('download/<int:question_id>/', views.download, name='download'),
    path('<int:answer_id>/answer_delete/',views.answer_delete, name="answer_delete"),
    # path('download/%3Fid=<int:question_id>/', views.download, name='download'),
    # path('download/', views.download, name='download'),
    # path('document/<int:document_id>/', FileDownloadView.as_view(), name="download"),
]

config/urls.py
from xml.etree.ElementInclude import include # 이진호가 추가함
from django.contrib import admin
from django.urls import path, include
from main import views
from userapp import views #이진호가 추가함
from django.conf.urls.static import static #이진호 추가 필수
from django.conf import settings #이진호 추가 필수
# from . import views as config_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('auth/', include('userapp.urls')),
    path('rank/', include('rank.urls')),
    path('quiz/', include('Quiz.urls')),
    path('blog/', include('blog.urls')),
    path('file/', include('file.urls')),
    path('board/', include('board.urls')),
    path('freeboard/', include('freeboard.urls')),
    path('paging/', include('paging.urls')),
    path('study/', include('study.urls')),
    path('youtubeboard/', include('youtubeboard.urls')),
    path('chat/', include('chat.urls')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freeboard/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'freeboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('index2/', views.index2, name='index2'),
    path('<int:freewrite_id>/', views.detail, name='detail'),
    path(
        'comment/create/<int:freewrite_id>/', views.comment_create,
        name='comment_create'),
    path('freewrite/create/', views.freewrite_create, name='freewrite_create'),
    path('freewrite/create2/', views.freewrite_create2, name='freewrite_create2'),
    path('<int:freewrite_id>/update/',views.update, name="update"),
    path('<int:freewrite_id>/delete/',views.delete, name="delete"),
    path('<int:comment_id>/comment_delete/',views.comment_delete, name="comment_delete"),
]

main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'
urlpatterns = [
    path('index/', views.index , name="index"),
    path('index2/', views.index2 , name="index2"),
    path('search/',views.search,name='search')
    
]

rank/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "rank"

urlpatterns = [
    path('rank1_100/', views.rank1_100, name = "rank1_100"),
    path('rank2_100/', views.rank2_100, name = "rank2_100"),
    path('insert/', views.insert),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

youtubeboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "youtubeboard"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name = "index"),
    path('index2/', views.index2, name = "index2"),
]

freeboard/models.py
from django.db import models

class Freewrite(models.Model):
    free_subject = models.CharField(max_length=200)
    free_content = models.TextField()
    free_pub_date = models.DateTimeField()
    username = models.CharField(max_length=200)

class Comment(models.Model):
    freewrite = models.ForeignKey(Freewrite, on_delete=models.CASCADE)
    comment_content = models.TextField()
    comment_create_date = models.DateTimeField()
    username = models.CharField(max_length=200)

freeboard/forms.py
from django import forms
from .models import Freewrite, Comment

class FreewriteForm(forms.ModelForm):
    
    class Meta:
        model = Freewrite
        fields = ['free_subject', 'free_content']
       
        labels = {
            'free_subject': '제목',
            'free_content': '내용',
        }


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['comment_content']
        labels = {
        'comment_content': '댓글내용',
        }

freeboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Freewrite,Comment
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.shortcuts import redirect
from userapp.models import User
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required #로그인여부

def index(request):
    now_page = request.GET.get('page', 1)
    freewrite_list = Freewrite.objects.order_by('-free_pub_date')
    p = Paginator(freewrite_list, 10)
    freeinfo = p.get_page(now_page)
    start_page = (int(now_page) - 1) // 10 * 10 + 1
    end_page = start_page + 9
    if end_page > p.num_pages:
        end_page = p.num_pages

    context = {'freeinfo': freeinfo,
        'page_range' : range(start_page, end_page + 1)
    }
    return render(request, 'freeboard/freewrite_list.html', context)

def index2(request):
    now_page = request.GET.get('page', 1)
    freewrite_list = Freewrite.objects.order_by('-free_pub_date')
    p = Paginator(freewrite_list, 10)
    freeinfo = p.get_page(now_page)
    start_page = (int(now_page) - 1) // 10 * 10 + 1
    end_page = start_page + 9
    if end_page > p.num_pages:
        end_page = p.num_pages

    context = {'freeinfo': freeinfo,
        'page_range' : range(start_page, end_page + 1)
    }
    return render(request, 'freeboard/freewrite_list2.html', context)


def detail(request, freewrite_id):
    freewrite = get_object_or_404(Freewrite, id=freewrite_id)
    context = {
        'freewrite': freewrite
    }
    return render(request, 'freeboard/freewrite_detail.html', context)


from .forms import CommentForm
@login_required (login_url='userapp:login')
def comment_create(request, freewrite_id):
    freewrite = get_object_or_404(Freewrite, pk=freewrite_id)
    
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comment_create_date = timezone.now()
            comment.freewrite = freewrite
            comment.username = request.user.username
            comment.save()
            return redirect('freeboard:detail', freewrite_id=freewrite.id)
    else:
        form = CommentForm()
    
    context = {'freewrite': freewrite, 'form': form}
    
    return render(request, 'freeboard/freewrite_detail.html', context)


from .forms import FreewriteForm
from userapp.models import User
@login_required (login_url='userapp:login')
def freewrite_create(request):
    user = User.objects.get(username = request.user.username)
    if request.method == 'POST':
        form = FreewriteForm(request.POST)
        if form.is_valid():
            freewrite = form.save(commit=False)
            freewrite.free_pub_date = timezone.now()
            freewrite.username = request.user.username
            freewrite.save()
            user.score = user.score + 5
            user.save()
            return redirect('freeboard:index')
    else:
        form = FreewriteForm()

    context = {'form': form}

    return render(request, 'freeboard/freewrite_form.html', context)


@login_required (login_url='userapp:login2')
def freewrite_create2(request):
    user = User.objects.get(username = request.user.username)
    if request.method == 'POST':
        form = FreewriteForm(request.POST)
        if form.is_valid():
            freewrite = form.save(commit=False)
            freewrite.free_pub_date = timezone.now()
            freewrite.username = request.user.username
            freewrite.save()
            user.score = user.score + 5
            user.save()
            return redirect('freeboard:index2')
    else:
        form = FreewriteForm()

    context = {'form': form}

    return render(request, 'freeboard/freewrite_form2.html', context)


def update(request, freewrite_id):
    freewrite = Freewrite.objects.get(id=freewrite_id)
    if(freewrite.username == request.user.username):
        if request.method == "POST":
            freewrite.free_subject = request.POST['subject']
            freewrite.free_content = request.POST['content']
            freewrite.free_pub_date = timezone.now()
            
            freewrite.save()
            return redirect('freeboard:index')
        else:
            freewrite=Freewrite()
            return render(request, 'freeboard/update.html', {'freewrite':freewrite})
    else :
        return render(request, 'freeboard/warning.html')


def delete(request, freewrite_id):
    freewrite = Freewrite.objects.get(id=freewrite_id)
    if(freewrite.username == request.user.username):
        freewrite.delete()
        return redirect('freeboard:index')
    return render(request, 'freeboard/warning.html')


def comment_delete(request,comment_id):
    comment = Comment.objects.get(id=comment_id)
    if(comment.username == request.user.username):
        comment.delete()
        return redirect('freeboard:index')
    return render(request, 'freeboard/warning.html')

freeboard/templates/freeboard/freewrite_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<!doctype html>
<html lang="en">

<head>
    <title>자유게시판 - 게시글</title>
    <meta charset="utf-8">
    <link rel ="icon" type="image/x-icon" href="/static/img/ktlogo.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   
    <link rel="stylesheet" href="/static/css/style.css"> 
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/static/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/style_rank.css" type="text/css">
</head>

<body>

        <!-- Header Section Begin -->
        <header class="header">
            <div class="header__top">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="header__top__left">
                                <ul>
                                 
                                    
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="header__top__right">
                                <div class="header__top__right__social">
                                    <a href="https://instagram.com/aivlestory?utm_medium=copy_link "target='_blank' ><i class="fa fa-instagram fa-2x" aria-hidden= "true"></i></a>
                                    <a href="https://classum.com/"target='_blank' ><i class="fa fa-copyright fa-2x" aria-hidden="true"></i></a>
                                    <a href="https://blog.naver.com/porory_rei"target='_blank' ><i class="fa fa-bold fa-2x" aria-hidden="true"></i></a>
                                    <a href="https://ktedu.kt.com/aivle/about.html"target='_blank' ><i class="fa fa-home fa-2x" aria-hidden="true"></i></a>
                                </div>
                                <div class="header__top__right__language">
                                    <img src="img/language.png"alt="">
                                    <div>AI 개발자</div>
                                    <span class="arrow_carrot-down"></span>
                                    <ul>
                                        <li><a href="{% url 'rank:rank1_100' %}">AI 개발자</a></li>
                                        <li><a href="{% url 'rank:rank2_100' %}">DX 컨설턴트</a></li>
                                    </ul>
                                </div>
                    
                                    {% if user.is_authenticated %}
                                      
                                    <div class="header__top__right__auth">
                                        <a href="{% url 'userapp:logout' %}"><i class="fa fa-user"></i> logout</a>
                                    </div> 
                                    
                                   
                                    
      
                                    {% else %}
                                    <div class="header__top__right__auth">
                                        <a href="{% url 'userapp:login' %}"><i class="fa fa-user"></i> Login</a>
                                    </div>
                                    {% endif %}
      
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="header__logo">
                            <a href="{% url 'main:index' %}"><img src="/static/img/aivle.PNG" class="mt-2"></a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <nav class="header__menu">
                            <ul>
                                <li class="active"><a href="{% url 'main:index' %}">홈</a></li>
                                <li><a href="/chat/chat_1">채팅</a></li>
                                <li><a href="#">커뮤니티</a>
                                    <ul class="header__menu__dropdown">
                                       
                                        <li><a href="{% url 'board:index' %}">Q&A</a></li>
                                        <li><a href="{% url 'freeboard:index' %}">자유게시판</a></li>
                                        <li><a href="{% url 'blog:index' %}">정보방</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'rank:rank1_100' %}">랭킹 TOP 100</a></li>
                                  <li><a href="">학습</a>
                                      <ul class="header__menu__dropdown">
                                          <li><a href="{% url 'study:studying' %}">AIVLE 강의</a></li>
                                          <li><a href="{% url 'youtubeboard:index' %}">YOUTUBE 강의</a></li>   
                                      
                                      </ul>   
                              
                                  
                              </li>
                                <li><a href="/quiz/main">퀴즈</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div class="col-lg-3">
                        <div class="header__cart">
                            
                              <a><i class="fa fa-user-circle fa-2x" aria-hidden= "true"></i></a>
                              <b>　{{user.username}}님</b>　 <b>score:</b> <span>{{user.score}}</span>
                           
                            
                        </div>
                    </div>
                </div>
                <div class="humberger__open">
                    <i class="fa fa-bars"></i>
                </div>
            </div>
        </header>
        <!-- Header Section End -->
      

<div class="container my-3">
    <br>
    
    <br>
    
    <h3 class="border-bottom py-2"> <img src="/static/img/say.png"> <b>{{ freewrite.free_subject }}</b>
        <br>
    </h3>
    
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <b style='color: #000000'>
                작성자 ID : <b>{{ freewrite.username }}</b>
        </div>
    
        <div class="card-text" style="white-space: pre-line;">
            　{{ freewrite.free_content }}
        </div>
        <div class="card-body">
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
    
    
                    {{ freewrite.free_pub_date }}
                    <br><br>
    
                </div>
               
            </div>
        </div>
       
    </div>
    <div style="float:right">
    <a href="{% url 'freeboard:update' freewrite.id %}" class="btn btn-primary">수정</a>
    <a href="{% url 'freeboard:delete' freewrite.id %}" class="btn btn-primary">삭제</a>
    </div>
    <br><br>
    <h4 class="border-bottom my-2 py-2">
        <div><img src="/static/img/reply.png"><b>
                등록된 댓글</div>
        </b>
    </h4>
    
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"> <span
                    style="background: linear-gradient(to top, #FFE400 30%, transparent 70%)">{{freewrite.comment_set.count}}개</span>의
                댓글</h6>
        </div>
        <div class="card-body">
    
            <div>
    
            </div>
    
            {% for comment in freewrite.comment_set.all %}
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <b style='color: #FF1244'>
                        작성자 : {{ comment.username }} </b>
                        <a href="{% url 'freeboard:comment_delete' comment.id %}" class="btn btn-primary" style="float:right"onClick="alert('삭제되었습니다.')">삭제</a>
                </div>
    
                <div class="card-text" style="white-space: pre-line;">
                    　 {{ comment.comment_content }}
                </div>
                <div class="card-body" >
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2">
    
    
                            {{ comment.comment_create_date }}
                            <br><br>
    
                        </div>
    
                    </div>
                </div>
            </div>
            {% endfor %}
    <form action="{% url 'freeboard:comment_create' freewrite.id %}" method="post" class="my-3">
        {% csrf_token %}

        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="form-group">
            <textarea name="comment_content" id="comment_content" class="form-control" placeholder="댓글을 입력하세요" rows="3"></textarea>
        </div>
        <div style='text-align:right;'>
            <input type="submit" value="댓글등록" class="btn btn-primary">
            <a href="{% url 'freeboard:index' %}" class="btn btn-primary">
                목록으로
            </a>
            
        </div>
    </form>
    <br><br>
    </div>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/main.js"></script>
</body>

freeboard/templates/freeboard/freewrite_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<!doctype html>
<html lang="en">

<head>
    <title>자유게시판 - 목록</title>
    <meta charset="utf-8">
    <link rel ="icon" type="image/x-icon" href="/static/img/ktlogo.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   
    <link rel="stylesheet" href="/static/css/style.css"> 
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/static/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/style_rank.css" type="text/css">
</head>

<body>

        <!-- Header Section Begin -->
        <header class="header">
            <div class="header__top">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="header__top__left">
                                <ul>
                                 
                                    
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="header__top__right">
                                <div class="header__top__right__social">
                                    <a href="https://instagram.com/aivlestory?utm_medium=copy_link "target='_blank' ><i class="fa fa-instagram fa-2x" aria-hidden= "true"></i></a>
                                    <a href="https://classum.com/"target='_blank' ><i class="fa fa-copyright fa-2x" aria-hidden="true"></i></a>
                                    <a href="https://blog.naver.com/porory_rei"target='_blank' ><i class="fa fa-bold fa-2x" aria-hidden="true"></i></a>
                                    <a href="https://ktedu.kt.com/aivle/about.html"target='_blank' ><i class="fa fa-home fa-2x" aria-hidden="true"></i></a>
                                </div>
                                <div class="header__top__right__language">
                                    <img src="img/language.png"alt="">
                                    <div>AI 개발자</div>
                                    <span class="arrow_carrot-down"></span>
                                    <ul>
                                        <li><a href="{% url 'main:index' %}">AI 개발자</a></li>
                                        <li><a href="{% url 'main:index2' %}">DX 컨설턴트</a></li>
                                    </ul>
                                </div>
                    
                                    {% if user.is_authenticated %}
                                      
                                    <div class="header__top__right__auth">
                                        <a href="{% url 'userapp:logout' %}"><i class="fa fa-user"></i> logout</a>
                                    </div> 
                                    
                                   
                                    
      
                                    {% else %}
                                    <div class="header__top__right__auth">
                                        <a href="{% url 'userapp:login' %}"><i class="fa fa-user"></i> Login</a>
                                    </div>
                                    {% endif %}
      
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="header__logo">
                            <a href="{% url 'main:index' %}"><img src="/static/img/aivle.PNG" class="mt-2"></a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <nav class="header__menu">
                            <ul>
                                <li class="active"><a href="{% url 'main:index' %}">홈</a></li>
                                <li><a href="/chat/chat_1">채팅</a></li>
                                <li><a href="#">커뮤니티</a>
                                    <ul class="header__menu__dropdown">
                                       
                                        <li><a href="{% url 'board:index' %}">Q&A</a></li>
                                        <li><a href="{% url 'freeboard:index' %}">자유게시판</a></li>
                                        <li><a href="{% url 'blog:index' %}">정보방</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'rank:rank1_100' %}">랭킹 TOP 100</a></li>
                                  <li><a href="">학습</a>
                                      <ul class="header__menu__dropdown">
                                          <li><a href="{% url 'study:studying' %}">AIVLE 강의</a></li>
                                          <li><a href="{% url 'youtubeboard:index' %}">YOUTUBE 강의</a></li>   
                                      
                                      </ul>   
                              
                                  
                              </li>
                                <li><a href="/quiz/main">퀴즈</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div class="col-lg-3">
                        <div class="header__cart">
                            
                              <a><i class="fa fa-user-circle fa-2x" aria-hidden= "true"></i></a>
                              <b>　{{user.username}}님</b>　 <b>score:</b> <span>{{user.score}}</span>
                           
                            
                        </div>
                    </div>
                </div>
                <div class="humberger__open">
                    <i class="fa fa-bars"></i>
                </div>
            </div>
        </header>
        <!-- Header Section End -->
      

<div class="container my-3">
    <h3 class="heading-section">자유게시판 </h3><br>
    <div class="row">
        <div class="col-md-12">
    <table class="table table-hover">

        <thead class="thead-primary">
            <tr>
                <th width="4%">번호</th>
                <th width="30%">　　　　　　　　　　　제목</th>
                <th width="10%">　　　작성자</th>
                <th width="30%">　　　　　　　　작성일시</th>
      
            </tr>
        </thead>
        <tbody>
            {% if freeinfo %}
          
                {% for freewrite in freeinfo %}
                <tr>
                    <td>　{{ forloop.revcounter }}</td>
                    <td>
                        <a href="{% url 'freeboard:detail' freewrite.id %}">
                            　　　　　　　 {{ freewrite.free_subject }}
                        </a>
                    </td>
                    <td>
                        　　　 {{freewrite.username}}
                    </td>
                    <td>　　　　　　　　{{ freewrite.free_pub_date }}</td>
                </tr>
                
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">글이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
        </table>
        
        <div style='text-align:center;'>
            <ul class='pagination'>
                {% for i in page_range %}
                <li>
                    <a href='{% url "freeboard:index" %}?page={{ i }}'>
                    {{ i }}
                </a>
                </li>
                {% endfor %}
                </ul>
            </div>
        <div style='text-align:right;'>
            <a href="{% url 'freeboard:freewrite_create' %}" class="btn btn-primary">
                글쓰기
            </a>
            <a href="{% url 'freeboard:index' %}" class="btn btn-primary">
                목록으로
            </a>
        </div>
        <br><br>
    </div>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/main.js"></script>
</body>

freeboard/templates/freeboard/warning.html
<script>
    alert("권한이 없습니다.")
    window.history.back() 
</script>