Quiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('main/', views.main),
    path('main2/', views.main2),
]

blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'
urlpatterns = [
    path('index/',views.index, name='index'),
    path('index2/',views.index2, name='index2'),
]

board/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

# from .views import FileDownloadView

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('index2/', views.index2, name='index2'),
    path('<int:question_id>/', views.detail, name='detail'),
    path(
        'answer/create/<int:question_id>/', views.answer_create,
        name='answer_create'),
    # path('question/create/', views.question_create, name='question_create'),

    path('<int:question_id>/update/',views.update, name="update"),
    path('<int:question_id>/delete/',views.delete, name="delete"),
    path('upload3/', views.upload3, name='upload3'),
    path('upload4/', views.upload4, name='upload4'),
    path('download/<int:question_id>/', views.download, name='download'),
    path('<int:answer_id>/answer_delete/',views.answer_delete, name="answer_delete"),
    # path('download/%3Fid=<int:question_id>/', views.download, name='download'),
    # path('download/', views.download, name='download'),
    # path('document/<int:document_id>/', FileDownloadView.as_view(), name="download"),
]

config/urls.py
from xml.etree.ElementInclude import include # 이진호가 추가함
from django.contrib import admin
from django.urls import path, include
from main import views
from userapp import views #이진호가 추가함
from django.conf.urls.static import static #이진호 추가 필수
from django.conf import settings #이진호 추가 필수
# from . import views as config_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('auth/', include('userapp.urls')),
    path('rank/', include('rank.urls')),
    path('quiz/', include('Quiz.urls')),
    path('blog/', include('blog.urls')),
    path('file/', include('file.urls')),
    path('board/', include('board.urls')),
    path('freeboard/', include('freeboard.urls')),
    path('paging/', include('paging.urls')),
    path('study/', include('study.urls')),
    path('youtubeboard/', include('youtubeboard.urls')),
    path('chat/', include('chat.urls')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'
urlpatterns = [
    path('index/', views.index , name="index"),
    path('index2/', views.index2 , name="index2"),
    path('search/',views.search,name='search')
    
]

rank/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "rank"

urlpatterns = [
    path('rank1_100/', views.rank1_100, name = "rank1_100"),
    path('rank2_100/', views.rank2_100, name = "rank2_100"),
    path('insert/', views.insert),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

study/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
app_name = "study"

urlpatterns = [
    path('studying/', views.studying, name = "studying"),
    path('studying2/', views.studying2, name = "studying2"),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

youtubeboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "youtubeboard"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name = "index"),
    path('index2/', views.index2, name = "index2"),
]

study/models.py
from django.db import models

# Create your models here.

study/views.py
from django.shortcuts import render
from django.http import HttpResponse
# from .models import rank_data
from django.db import connection
from userapp.models import User
# Create your views here.

def studying(request):
    return render(
        request,
        'study/studying.html',
    )

def studying2(request):
    return render(
        request,
        'study/studying2.html',
    )

study/templates/study/studying.html
{% load static %}

<!doctype html>
<html lang="en">

  <head>
     <title>AIVLE 강의</title>
     <link rel ="icon" type="image/x-icon" href="/static/img/ktlogo.ico">
    <meta charset="utf-8">
   
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   
   <link rel="stylesheet" href="/static/css/style.css"> 
   <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/static/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/style_rank.css" type="text/css">
   
   </head>

   <body>
    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                            <ul>
                              
                                
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="https://instagram.com/aivlestory?utm_medium=copy_link "target='_blank'><i class="fa fa-instagram fa-2x" aria-hidden= "true"></i></a>
                                <a href="https://classum.com/"target='_blank'><i class="fa fa-copyright fa-2x" aria-hidden="true"></i></a>
                                <a href="https://blog.naver.com/porory_rei"target='_blank'><i class="fa fa-bold fa-2x" aria-hidden="true"></i></a>
                                <a href="https://ktedu.kt.com/aivle/about.html"target='_blank'><i class="fa fa-home fa-2x" aria-hidden="true"></i></a>
                            </div>
                            <div class="header__top__right__language">
                                <img src="img/language.png"alt="">
                                <div>AI 개발자</div>
                                <span class="arrow_carrot-down"></span>
                                <ul>
                                    <li><a href="#">AI 개발자</a></li>
                                    <li><a href="{% url 'study:studying2'%}">DX 컨설턴트</a></li>
                                </ul>
                            </div>
                
                                {% if user.is_authenticated %}
                                  
                                <div class="header__top__right__auth">
                                    <a href="{% url 'userapp:logout' %}"><i class="fa fa-user"></i> logout</a>
                                </div> 
                                
                                
                                
  
                                {% else %}
                                <div class="header__top__right__auth">
                                    <a href="{% url 'userapp:login' %}"><i class="fa fa-user"></i> Login</a>
                                </div>
                                {% endif %}
  
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="{% url 'main:index' %}"><img src="/static/img/aivle.PNG" class="mt-2"></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="{% url 'main:index' %}">홈</a></li>
                            <li><a href="/chat/chat_1">채팅</a></li>
                            <li><a href="#">커뮤니티</a>
                                <ul class="header__menu__dropdown">
                                    
                                    <li><a href="{% url 'board:index' %}">Q&A</a></li>
                                    <li><a href="{% url 'freeboard:index' %}">자유게시판</a></li>
                                    <li><a href="{% url 'blog:index' %}">정보방</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'rank:rank1_100' %}">랭킹 TOP 100</a></li>
                            <li><a href="">학습</a>
                                  <ul class="header__menu__dropdown">
                                      <li><a href="{% url 'study:studying' %}">AIVLE 강의</a></li>
                                      <li><a href="{% url 'youtubeboard:index' %}">YOUTUBE 강의</a></li>   
                          
                              </ul>
                          </li>      
                            <li><a href="/quiz/main">퀴즈</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    <div class="header__cart">
                        <ul>
                          <a><i class="fa fa-user-circle fa-2x" aria-hidden= "true"></i></a>
                          <b>　{{user.username}}님</b>　 <b>score:</b> <span>{{user.score}}</span>
                        </ul>
                        
                    </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

  <section class="ftco-section">
    <div class="container">
       <div class="row justify-content-center">
          <div class="col-md-6 text-center mb-5">
             <h2 class="heading-section">Aivler's Studying Cafe</h2>
          </div>
       </div>
       <div class="row">
          <div class="col-md-12">
             <div class="table-wrap">
                <table class="table">
                  <thead class="thead-primary">
                    <tr>
                      <th>강의</th>
                      <th>강사</th>
                      <th>강의 기간</th>
                      <th>PDF 다운</th>
                    </tr>
                  </thead>
                  <tbody>
                     <tr>
                         <th scope="row">IT 트렌드 맛보기</th>
                         <td>이두원</td>
                         <td>2021년 12월 14일</td>
                         <td> <a href="https://drive.google.com/file/d/1tG0dGDOHc8jQbDWZFd6a_wbN7ZBL8KLQ/view?usp=sharing" target='_blank'>
                            <img src="/static/images/pdf_down1.png"> </td>                   
                      </tr>
                      <tr>
                        <th scope="row">IT프로젝트 관리 도구</th>
                        <td>이고잉</td>
                        <td>2021년 12월 15일</td>
                        <td> <a href="https://drive.google.com/file/d/1j4ekc0WNI7QbESmoNCJVTR7yYVAyThbO/view?usp=sharing" target='_blank'>
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>
                     <tr>
                        <th scope="row">SQL</th>
                        <td>이장래</td>
                        <td>2021년 12월 16일 ~ 17일</td>
                        <td> <a href="https://drive.google.com/file/d/1igTwo5Op3IGRgI3nL11bbXRffEvLMPe8/view?usp=sharing" target='_blank'>
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>
                     <tr>
                        <th scope="row">IT인프라 이해</th>
                        <td>계영수</td>
                        <td>2021년 12월 20일 ~ 21일</td>
                        <td> <a href="https://drive.google.com/file/d/1r4F734_nKKuV8p2umGWEAXkjW0LK5E0s/view?usp=sharing" target='_blank'> 
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>
                     <tr>
                        <th scope="row">WEB,WAS,DB 3TIER</th>
                        <td>소영재</td>
                        <td>2021년 12월 22일 ~ 24일</td>
                        <td> <a href="https://drive.google.com/file/d/1_ZR15B05roT32SH4VdmFo6_3mCG7hppq/view?usp=sharing" target='_blank'>
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>
                     <tr>
                        <th scope="row">가상화&클라우드</th>
                        <td>윤혜식</td>
                        <td>2021년 12월 27일 ~ 28일</td>
                        <td> <a href="https://drive.google.com/file/d/1EJIdrbTizAy-kMFYEvroSEuASTSsrj8z/view?usp=sharing" target='_blank'>
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>
                     <tr>
                        <th scope="row">UI/UX 기획</th>
                        <td>김수연</td>
                        <td>2021년 12월 29일 ~ 31일</td>
                        <td> <a href="https://drive.google.com/file/d/1GlJJe3ymhdNy2oSUXmEtMIgnb3TZzSPJ/view?usp=sharing" target='_blank'>
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>
                     <tr>
                        <th scope="row">웹 개발용 프로그래밍 언어 개론</th>
                        <td>이성구</td>
                        <td>2022년 1월 3일 ~ 7일</td>
                        <td> <a href="https://drive.google.com/file/d/1Te3PIEtHf6I3_GEjEe6eo02AljTtmKiV/view?usp=sharing" target='_blank'>
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>
                     <tr>
                        <th scope="row">Python 문법 기초</th>
                        <td>김건영</td>
                        <td>2022년 1월 10일 ~ 11일</td>
                        <td> <a href="https://drive.google.com/file/d/1oO98kKKNanCSr0P8k8z6Dm53ay550CBe/view?usp=sharing" target='_blank'>
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>
                     <tr>
                        <th scope="row">Python 기반 자료구조</th>
                        <td>이홍주</td>
                        <td>2022년 1월 12일 ~ 14일</td>
                        <td> <a href="https://drive.google.com/file/d/1afCJU_SRWMN3byyORjRbc353PyD5QGXZ/view?usp=sharing" target='_blank'>
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>
                     <tr>
                        <th scope="row">Django를 활용한 Web App</th>
                        <td>김남현</td>
                        <td>2022년 1월 17일 ~ 21일</td>
                        <td> <a href="https://drive.google.com/file/d/1ioFq_x-a_Uq8BvZBgBgQ3VuntPSIXTvE/view?usp=sharing" target='_blank'>
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>
                     <tr>
                        <th scope="row">전체 교육 과정</th>
                        <td>KT AIVLE</td>
                        <td></td>
                        <td> <a href="https://docs.google.com/spreadsheets/d/1naUm4zrcBSAqUqL2l4fXLdshMxs0JEQH/edit?usp=sharing&ouid=115816752512693076192&rtpof=true&sd=true" target='_blank'>
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>

                  </tbody>
                </table>
             </div>
          </div>
       </div>
    </div>
 </section>

 <script src="/static/js/jquery.min.js"></script>
<script src="/static/js/popper.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/main.js"></script>

</body>
</html>

study/templates/study/studying2.html
{% load static %}

<!doctype html>
<html lang="en">

  <head>
     <title>AIVLE 강의</title>
     <link rel ="icon" type="image/x-icon" href="/static/img/ktlogo.ico">
    <meta charset="utf-8">
   
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   
   <link rel="stylesheet" href="/static/css/style2.css" type="text/css"> 
   <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/static/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/style_rank2.css" type="text/css">
   

   

   </head>
   <body>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                            <ul>
                              
                                
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="https://instagram.com/aivlestory?utm_medium=copy_link "target='_blank'><i class="fa fa-instagram fa-2x" aria-hidden= "true"></i></a>
                                <a href="https://classum.com/"target='_blank'><i class="fa fa-copyright fa-2x" aria-hidden="true"></i></a>
                                <a href="https://blog.naver.com/porory_rei"target='_blank'><i class="fa fa-bold fa-2x" aria-hidden="true"></i></a>
                                <a href="https://ktedu.kt.com/aivle/about.html"target='_blank'><i class="fa fa-home fa-2x" aria-hidden="true"></i></a>
                            </div>
                            <div class="header__top__right__language">
                                <img src="img/language.png"alt="">
                                <div>DX 컨설턴트</div>
                                <span class="arrow_carrot-down"></span>
                                <ul>
                                    <li><a href="#">DX 컨설턴트</a></li>
                                    <li><a href="{% url 'study:studying'%}">AI 개발자</a></li>
                                </ul>
                            </div>
                
                                {% if user.is_authenticated %}
                                  
                                <div class="header__top__right__auth">
                                    <a href="{% url 'userapp:logout' %}"><i class="fa fa-user"></i> logout</a>
                                </div> 
                                
                                
                                
  
                                {% else %}
                                <div class="header__top__right__auth">
                                    <a href="{% url 'userapp:login2' %}"><i class="fa fa-user"></i> Login</a>
                                </div>
                                {% endif %}
  
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="{% url 'main:index2' %}"><img src="/static/img/aivle.PNG" class="mt-2"></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="{% url 'main:index2' %}">홈</a></li>
                            <li><a href="/chat/chat_1">채팅</a></li>
                            <li><a href="#">커뮤니티</a>
                                <ul class="header__menu__dropdown">
                                    
                                    <li><a href="{% url 'board:index2' %}">Q&A</a></li>
                                    <li><a href="{% url 'freeboard:index2' %}">자유게시판</a></li>
                                    <li><a href="{% url 'blog:index2' %}">정보방</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'rank:rank2_100' %}">랭킹 TOP 100</a></li>
                            <li><a href="">학습</a>
                                  <ul class="header__menu__dropdown">
                                      <li><a href="{% url 'study:studying2' %}">AIVLE 강의</a></li>
                                      <li><a href="{% url 'youtubeboard:index2' %}">YOUTUBE 강의</a></li>   
                          
                              </ul>
                          </li>      
                            <li><a href="/quiz/main2">퀴즈</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    <div class="header__cart">
                        <ul>
                          <a><i class="fa fa-user-circle fa-2x" aria-hidden= "true"></i></a>
                          <b>　{{user.username}}님</b>　 <b>score:</b> <span>{{user.score}}</span>
                        </ul>
                        
                    </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

  <section class="ftco-section">
    <div class="container">
       <div class="row justify-content-center">
          <div class="col-md-6 text-center mb-5">
            <a href="#"><img src="/static/images/book.png" alt="">
             <h2 class="heading-section">Aivler's Studying Cafe</h2>
          </div>
       </div>
       <div class="row">
          <div class="col-md-12">
             <div class="table-wrap">
                <table class="table">
                  <thead class="thead-primary">
                    <tr>
                        <th>강의</th>
                        <th>강사</th>
                        <th>강의 기간</th>
                        <th>PDF 다운</th>
                      
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                        <th scope="row">IT 트렌드 맛보기</th>
                        <td>이두원</td>
                        <td>2021년 12월 14일</td>
                        <td> <a href="https://drive.google.com/file/d/1tG0dGDOHc8jQbDWZFd6a_wbN7ZBL8KLQ/view?usp=sharing" target='_blank'>
                           <img src="/static/images/pdf_down1.png"> </td>                   
                     </tr>
                     <tr>
                       <th scope="row">IT프로젝트 관리 도구</th>
                       <td>이고잉</td>
                       <td>2021년 12월 15일</td>
                       <td> <a href="https://drive.google.com/file/d/1j4ekc0WNI7QbESmoNCJVTR7yYVAyThbO/view?usp=sharing" target='_blank'>
                          <img src="/static/images/pdf_down1.png"> </td>                   
                    </tr>
                    <tr>
                       <th scope="row">SQL</th>
                       <td>이장래</td>
                       <td>2021년 12월 16일 ~ 17일</td>
                       <td> <a href="https://drive.google.com/file/d/1igTwo5Op3IGRgI3nL11bbXRffEvLMPe8/view?usp=sharing" target='_blank'>
                          <img src="/static/images/pdf_down1.png"> </td>                   
                    </tr>
                    <tr>
                       <th scope="row">IT인프라 이해</th>
                       <td>계영수</td>
                       <td>2021년 12월 20일 ~ 21일</td>
                       <td> <a href="https://drive.google.com/file/d/1r4F734_nKKuV8p2umGWEAXkjW0LK5E0s/view?usp=sharing" target='_blank'> 
                          <img src="/static/images/pdf_down1.png"> </td>                   
                    </tr>
                    <tr>
                       <th scope="row">WEB,WAS,DB 3TIER</th>
                       <td>소영재</td>
                       <td>2021년 12월 22일 ~ 24일</td>
                       <td> <a href="https://drive.google.com/file/d/1_ZR15B05roT32SH4VdmFo6_3mCG7hppq/view?usp=sharing" target='_blank'>
                          <img src="/static/images/pdf_down1.png"> </td>                   
                    </tr>
                    <tr>
                       <th scope="row">가상화&클라우드</th>
                       <td>윤혜식</td>
                       <td>2021년 12월 27일 ~ 28일</td>
                       <td> <a href="https://drive.google.com/file/d/1EJIdrbTizAy-kMFYEvroSEuASTSsrj8z/view?usp=sharing" target='_blank'>
                          <img src="/static/images/pdf_down1.png"> </td>                   
                    </tr>
                    <tr>
                       <th scope="row">UI/UX 기획</th>
                       <td>김수연</td>
                       <td>2021년 12월 29일 ~ 31일</td>
                       <td> <a href="https://drive.google.com/file/d/1GlJJe3ymhdNy2oSUXmEtMIgnb3TZzSPJ/view?usp=sharing" target='_blank'>
                          <img src="/static/images/pdf_down1.png"> </td>                   
                    </tr>
                    <tr>
                       <th scope="row">웹 개발용 프로그래밍 언어 개론</th>
                       <td>이성구</td>
                       <td>2022년 1월 3일 ~ 7일</td>
                       <td> <a href="https://drive.google.com/file/d/1Te3PIEtHf6I3_GEjEe6eo02AljTtmKiV/view?usp=sharing" target='_blank'>
                          <img src="/static/images/pdf_down1.png"> </td>                   
                    </tr>
                    <tr>
                       <th scope="row">Python 문법 기초</th>
                       <td>김건영</td>
                       <td>2022년 1월 10일 ~ 11일</td>
                       <td> <a href="https://drive.google.com/file/d/1oO98kKKNanCSr0P8k8z6Dm53ay550CBe/view?usp=sharing" target='_blank'>
                          <img src="/static/images/pdf_down1.png"> </td>                   
                    </tr>
                    <tr>
                       <th scope="row">Python 기반 자료구조</th>
                       <td>이홍주</td>
                       <td>2022년 1월 12일 ~ 14일</td>
                       <td> <a href="https://drive.google.com/file/d/1afCJU_SRWMN3byyORjRbc353PyD5QGXZ/view?usp=sharing" target='_blank'>
                          <img src="/static/images/pdf_down1.png"> </td>                   
                    </tr>
                    <tr>
                       <th scope="row">Django를 활용한 Web App</th>
                       <td>김남현</td>
                       <td>2022년 1월 17일 ~ 21일</td>
                       <td> <a href="https://drive.google.com/file/d/1ioFq_x-a_Uq8BvZBgBgQ3VuntPSIXTvE/view?usp=sharing" target='_blank'>
                          <img src="/static/images/pdf_down1.png"> </td>                   
                    </tr>
                    <tr>
                       <th scope="row">전체 교육 과정</th>
                       <td>KT AIVLE</td>
                       <td></td>
                       <td> <a href="https://docs.google.com/spreadsheets/d/1naUm4zrcBSAqUqL2l4fXLdshMxs0JEQH/edit?usp=sharing&ouid=115816752512693076192&rtpof=true&sd=true" target='_blank'>
                          <img src="/static/images/pdf_down1.png"> </td>                   
                    </tr>
                  </tbody>
                </table>
             </div>
          </div>
       </div>
    </div>
 </section>

 <script src="/static/js/jquery.min.js"></script>
<script src="/static/js/popper.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/main.js"></script>

 </body>
</html>