Quiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('main/', views.main),
    path('main2/', views.main2),
]

blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'
urlpatterns = [
    path('index/',views.index, name='index'),
    path('index2/',views.index2, name='index2'),
]

board/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

# from .views import FileDownloadView

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('index2/', views.index2, name='index2'),
    path('<int:question_id>/', views.detail, name='detail'),
    path(
        'answer/create/<int:question_id>/', views.answer_create,
        name='answer_create'),
    # path('question/create/', views.question_create, name='question_create'),

    path('<int:question_id>/update/',views.update, name="update"),
    path('<int:question_id>/delete/',views.delete, name="delete"),
    path('upload3/', views.upload3, name='upload3'),
    path('upload4/', views.upload4, name='upload4'),
    path('download/<int:question_id>/', views.download, name='download'),
    path('<int:answer_id>/answer_delete/',views.answer_delete, name="answer_delete"),
    # path('download/%3Fid=<int:question_id>/', views.download, name='download'),
    # path('download/', views.download, name='download'),
    # path('document/<int:document_id>/', FileDownloadView.as_view(), name="download"),
]

config/urls.py
from xml.etree.ElementInclude import include # 이진호가 추가함
from django.contrib import admin
from django.urls import path, include
from main import views
from userapp import views #이진호가 추가함
from django.conf.urls.static import static #이진호 추가 필수
from django.conf import settings #이진호 추가 필수
# from . import views as config_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('auth/', include('userapp.urls')),
    path('rank/', include('rank.urls')),
    path('quiz/', include('Quiz.urls')),
    path('blog/', include('blog.urls')),
    path('file/', include('file.urls')),
    path('board/', include('board.urls')),
    path('freeboard/', include('freeboard.urls')),
    path('paging/', include('paging.urls')),
    path('study/', include('study.urls')),
    path('youtubeboard/', include('youtubeboard.urls')),
    path('chat/', include('chat.urls')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'
urlpatterns = [
    path('index/', views.index , name="index"),
    path('index2/', views.index2 , name="index2"),
    path('search/',views.search,name='search')
    
]

rank/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "rank"

urlpatterns = [
    path('rank1_100/', views.rank1_100, name = "rank1_100"),
    path('rank2_100/', views.rank2_100, name = "rank2_100"),
    path('insert/', views.insert),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

study/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
app_name = "study"

urlpatterns = [
    path('studying/', views.studying, name = "studying"),
    path('studying2/', views.studying2, name = "studying2"),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

youtubeboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "youtubeboard"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name = "index"),
    path('index2/', views.index2, name = "index2"),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db import connection
from sympy import content
from userapp.models import User
from board.models import Question
# Create your views here.
def index(request):
    rank_list = User.objects.all().order_by('-score')
    return render(
        request,
        'main/index.html',
        {'rank_list': rank_list}
    )

def index2(request):
    rank_list = User.objects.all().order_by('-score')
    return render(
        request,
        'main/index2.html',
        {'rank_list': rank_list}
    )

def search(request):
    if request.method == 'POST':
        search = request.POST.get('search')
        result=Question.objects.filter(subject__contains=search)
        return render(
                request,
                'main/show.html',
                {'data':result, 
                'search':search}
                
            )

    

main/templates/main/show.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<!doctype html>
<html lang="en">

<head>
    <title>Search</title>
    <meta charset="utf-8">
   
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/jinho.css"> 
    <link rel="stylesheet" href="/static/css/style.css"> 
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/static/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/style_rank.css" type="text/css">
</head>

<body>

       <!-- Header Section Begin -->
       <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                            <ul>
                             
                                
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="https://instagram.com/aivlestory?utm_medium=copy_link "target='_blank' ><i class="fa fa-instagram fa-2x" aria-hidden= "true"></i></a>
                                <a href="https://classum.com/"target='_blank' ><i class="fa fa-copyright fa-2x" aria-hidden="true"></i></a>
                                <a href="https://blog.naver.com/porory_rei"target='_blank' ><i class="fa fa-bold fa-2x" aria-hidden="true"></i></a>
                                <a href="https://ktedu.kt.com/aivle/about.html"target='_blank' ><i class="fa fa-home fa-2x" aria-hidden="true"></i></a>
                            </div>
                            <div class="header__top__right__language">
                                <img src="img/language.png"alt="">
                                <div>AI 개발자</div>
                                <span class="arrow_carrot-down"></span>
                                <ul>
                                    <li><a href="{% url 'rank:rank1_100' %}">AI 개발자</a></li>
                                    <li><a href="{% url 'rank:rank2_100' %}">DX 컨설턴트</a></li>
                                </ul>
                            </div>
                
                                {% if user.is_authenticated %}
                                  
                                <div class="header__top__right__auth">
                                    <a href="{% url 'userapp:logout' %}"><i class="fa fa-user"></i> logout</a>
                                </div> 
                                
                               
                                
  
                                {% else %}
                                <div class="header__top__right__auth">
                                    <a href="{% url 'userapp:login' %}"><i class="fa fa-user"></i> Login</a>
                                </div>
                                {% endif %}
  
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="{% url 'main:index' %}"><img src="/static/img/aivle.PNG" class="mt-2"></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="{% url 'main:index' %}">홈</a></li>
                            <li><a href="./shop-grid.html">채팅</a></li>
                            <li><a href="#">커뮤니티</a>
                                <ul class="header__menu__dropdown">
                                   
                                    <li><a href="{% url 'board:index' %}">Q&A</a></li>
                                    <li><a href="{% url 'freeboard:index' %}">자유게시판</a></li>
                                    <li><a href="{% url 'blog:index' %}">정보방</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'rank:rank1_100' %}">랭킹 TOP 100</a></li>
                              <li><a href="">학습</a>
                                  <ul class="header__menu__dropdown">
                                      <li><a href="{% url 'study:studying' %}">AIVLE 강의</a></li>
                                      <li><a href="{% url 'youtubeboard:index' %}">YOUTUBE 강의</a></li>   
                                  
                                  </ul>   
                          
                              
                          </li>
                            <li><a href="/quiz/main">퀴즈</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    <div class="header__cart">
                        
                          <a><i class="fa fa-user-circle fa-2x" aria-hidden= "true"></i></a>
                          <b>　{{user.username}}님</b>　 <b>score:</b> <span>{{user.score}}</span>
                       
                        
                    </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->
<div style="text-align:center">
    <h3 class="heading-section">"<mark>{{search}}</mark> "포함된 검색결과입니다.</h3>
    <br>
 </div>

<div class="container">
    <table class="board-table">
        <thead class="thead-primary">
            <tr>
                    <b><th scope="col" class="th-num">번호</th>
                    <th scope="col" class="th-title">제목</th>
                    <th scope="col" class="th-date">작성자</th>
                    <th scope="col" class="th-date">작성일지</th>
            </tr>
        </thead>
        <tbody>
                {% for item in data %}
                <tr>
                    <td> {{ item.id }}</td>
                    <td>
                    <a href="{% url 'board:detail' item.id %}">
                        {{ item.subject }}
                    </a>
                    </td>   
                    <td> {{item.username}}</td>
                    <td>{{item.pub_date}}</td>    
                   
                </tr>   
                {% endfor %}
            <tr>   
        </tr>
        </tbody>
        </table>
        <div style='text-align:center;'>
            <ul class='pagination'>
                {% for i in page_range %}
                <li>
                <a href='{% url "board:index" %}?page={{ i }}'>
                    {{ i }}
                </a>
                </li>
                {% endfor %}
                </ul>
            </div>
        
        <br><br>
    </div>

    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/main.js"></script>
</body>